services:
  propaganda-bot:
    image: pawelowczarczyk/discord-propaganda-bot:latest
    build: .
    container_name: propaganda-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # If the variable is in .env, it will be loaded automatically.
      # You can also override it here directly:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      # Timezone setting (optional, important for scheduling)
      - TZ=Europe/Warsaw
