services:
  propaganda-bot:
    image: pawelowczarczyk/discord-propaganda-bot:latest
    build: .
    container_name: propaganda-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DAILY_DISPATCH_COUNT=${DAILY_DISPATCH_COUNT:-3}
      - TZ=Europe/Warsaw
